name: simple_icons
description: The Simple Icon pack available as Flutter Icons. Provides over 1500 Free SVG icons for popular brands.
version: 4.20.0
homepage: https://jlnrrg.github.io/
repository: https://github.com/jlnrrg/simple_icons
environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  recase: ^4.0.0-nullsafety.0
  xml: ^5.0.2
flutter:
  fonts:
    - family: SimpleIcons
      fonts:
        - asset: fonts/SimpleIcons.ttf
